// Code generated by mockery v2.23.1. DO NOT EDIT.

package reader

import mock "github.com/stretchr/testify/mock"

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// ReadString provides a mock function with given fields:
func (_m *MockReader) ReadString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockReader_ReadString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadString'
type MockReader_ReadString_Call struct {
	*mock.Call
}

// ReadString is a helper method to define mock.On call
func (_e *MockReader_Expecter) ReadString() *MockReader_ReadString_Call {
	return &MockReader_ReadString_Call{Call: _e.mock.On("ReadString")}
}

func (_c *MockReader_ReadString_Call) Run(run func()) *MockReader_ReadString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_ReadString_Call) Return(_a0 string) *MockReader_ReadString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReader_ReadString_Call) RunAndReturn(run func() string) *MockReader_ReadString_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockReader(t mockConstructorTestingTNewMockReader) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
